### ISSUE TITLE
Custom app icon inquiry

### ISSUE THREAD

**Issue by ErrorErrorError** [Zabriskije/macOS-Icons#1]
Hello,

I was unable to find your personal email for this inquiry, but I was wondering if you accept any requests for creating a custom app icon for my open-source app called [Mochi](https://github.com/Mochi-Team/mochi).

I already made some mock-up app icon for my app, but I would like to have it done with someone with more experienced in designing.

If there's any way to personally contact you please let me know!

Thank you.

**Comment by Zabriskije** [comment]
Sure, you can contact me on Discord. I have the same username as here :)

**Comment by ErrorErrorError** [comment]
> Sure, you can contact me on Discord. I have the same username as here :)

Awesome! I'm `NotErik` on Discord.
